/*
-- Query: SELECT * FROM r9j86xrrany9tm7r.Reviews
LIMIT 0, 1000

-- Date: 2017-08-11 12:55
*/
INSERT INTO `Reviews` (`review_id`,`vendor_id`,`user_name`,`review_text`,`rateYoInput`,`user_id`) VALUES (1,2,'Novia Lim','If you grew up on fields of corn, eating what your family planted, moving halfway across the world to an urban center wouldn\'t change things. So, when Idzai Mubaiwa, 49, relocated to San Diego from her native Zimbabwe in 2002 with her husband and four daughters, finding land to farm was as important as finding good schools for her girls.\r\n\r\nShe got her start through the International Rescue Committee, with a 30- by 40-foot garden plot\' adjacent to her sister Tsitsi\'s. When her sister died from breast cancer, she took over her plot, then found land to farm in National City and just off Market Street. On her four plots she grows magnificent produce, including scallions, carrots, broccoli and greens, beets, kale, Swiss chard, tomatoes and celery, which she sells at the North Park farmers\' market, where she\'s been a vendor for four years.\r\n\r\nBefore her farming day begins, she drives an airport shuttle bus starting at 4am.\r\n\r\n\"Eventually, I\'d love to just do farming,\" she says. She\'d also like to have a small organic produce store in City Heights. In the meantime, she\'s eager to meet more chefs.\r\n\r\n\"I want to grow what they want to use.\"',4,NULL);
INSERT INTO `Reviews` (`review_id`,`vendor_id`,`user_name`,`review_text`,`rateYoInput`,`user_id`) VALUES (2,3,'Aithan Sampson','My favorite olive oil from The California Olive is a very mellow, light tasting oil that has an almost sweet \"nuttiness\" and a \"fruity\" scent reminiscent of green olives. With just a \"little bite,\" this olive oil is a great option for those seeking a more mild, everyday oil.',3,NULL);
INSERT INTO `Reviews` (`review_id`,`vendor_id`,`user_name`,`review_text`,`rateYoInput`,`user_id`) VALUES (3,6,'Samuel Jackson','I\'m new to San Diego and happened upon this humble blessing before heading home. It was very comforting to see that the community recognized and cherished the value of supporting local farmers and also the health benefits of eating organic from the earth. \r\n\r\nThe staff was enormously friendly and I truly felt welcomed into their shop. I was greeted with warm hellos from everyone. \r\n\r\nThe organizational layout of the shop is very simplistic and easy to sift through; this made shopping a breeze. \r\n\r\nI particularly loved the selection of veggies and fruits; these are their staple products. So, don\'t intend to stop here for detergents, knick-knacks or other \'random\' household items; this is a true farm-market. \r\n\r\nI especially liked their support for other local baked goods, like Dudley Farms pies and tarts. \r\nI fully endorse this establishment not only because eating local, organic and fresh is the new \'trend\'; but because it\'s the healthiest way of living for everyone.',4,NULL);
INSERT INTO `Reviews` (`review_id`,`vendor_id`,`user_name`,`review_text`,`rateYoInput`,`user_id`) VALUES (4,6,'Kelly Cherie','Always on the hunt for good, local, tree ripened fruit. As you may guess, we found some good ones here.\r\n\r\nDon\'t expect flawless beauties here. Our white peaches and nectaplums (yes, a cross of a nectarine and a plum) came definitely from humble homes, scarred badly.  But I really couldn\'t care less.  It is love at first bite. The only other option is to grow them yourself.  \r\n\r\nToo bad the orange colored peaches were not up to par. \r\n\r\nBut the other biggie?  Genuine Julian Pies here. Yesssss!\r\n\r\nStunning revelation.',3,NULL);
INSERT INTO `Reviews` (`review_id`,`vendor_id`,`user_name`,`review_text`,`rateYoInput`,`user_id`) VALUES (5,3,'Daniel Well','The Balsamic vinaigrette is amazing. I have tried a few flavors and couldn\'t settle on just one and it and ended up buying about 4 bottles. They are absolutely to die for and a great addition to every party or midnight snack!!!',3,NULL);
INSERT INTO `Reviews` (`review_id`,`vendor_id`,`user_name`,`review_text`,`rateYoInput`,`user_id`) VALUES (6,3,'Mary Grace','Can\'t speak to the quality or taste of the product, however the girl selling at the OB Farmers market is nothing short of a snotty witch. She\'s definitely in the wrong town with that attitude. I will never buy this product nor promote it within our community simply based on her negative energy. Bummer : (',0,NULL);
INSERT INTO `Reviews` (`review_id`,`vendor_id`,`user_name`,`review_text`,`rateYoInput`,`user_id`) VALUES (7,3,'Novia Lim','This was my first \"olive oil tasting\" ever and it was free.  The clerk working (I believe her name was Cindy) was fantastic. She was very knowledgeable of the various olive oils and how to pair them with all types of food.   You get to try four small samples (just a taste a couple of drops) of olive oils and then she would give you a sample with vinegar added.    My favorite was the \"Fresh Blood Orange\" olive oil.',4,NULL);
